project_id = "hwxxcprqxqznselwzghi"

[functions.gateway-status]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.send-sms-bulksms]
verify_jwt = false

[functions.send-quick-sms]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.cleanup-otps]
verify_jwt = true

[functions.bulksms-delivery-webhook]
verify_jwt = false

[functions.bulksms-balance]
verify_jwt = true

[functions.confirm-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = true

[functions.test-smtp]
verify_jwt = true

[functions.webhooks-simulate]
verify_jwt = false

[functions.campaigns-api]
verify_jwt = true

[functions.campaign-worker]
verify_jwt = false

[functions.campaign-scheduler]
verify_jwt = false