project_id = "hwxxcprqxqznselwzghi"

[functions.gateway-status]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.send-sms-bulksms]
verify_jwt = false

[functions.bulksms-delivery-webhook]
verify_jwt = false

[functions.bulksms-balance]
verify_jwt = false