// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwxxcprqxqznselwzghi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eHhjcHJxeHF6bnNlbHd6Z2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDA5NDUsImV4cCI6MjA2NzExNjk0NX0.mjm1kF6gI55F9DLYfueAVOKokvTY8_nv0sFvvG_ReQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});